package tech.sneakybuzz.artifact.model.enums;

public enum OnBoardingStatus {
  REGISTERED_NOT_VERIFIED,
  EMAIL_VERIFIED_NO_ROLE,
  ROLE_SELECTED_BUYER,
  BUYER_ONBOARDING_COMPLETE,
  ROLE_SELECTED_ARTIST,
  ARTIST_ONBOARDING_COMPLETE,
  ONBOARDING_SKIPPED
}
